config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :characters do
    resources :casts, only: [:new, :create]
  end

  resources :films do
    resources :casts, only: [:new, :create]
  end
  
  resources :casts, only: :destroy
  resources :genres, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cast.rb
class Cast < ApplicationRecord
  belongs_to :character
  belongs_to :film
  validates :character_id, uniqueness: { scope: :film_id, message: "Ya está en esta película"}
end

app/models/character.rb
class Character < ApplicationRecord
  has_many :casts
  has_many :films, through: :casts
  has_one_attached :photo

  validates :name, uniqueness: true, presence: :true
  validates :history, length: { minimum: 6 }

end

app/models/film.rb
class Film < ApplicationRecord
  has_many :casts, dependent: :destroy
  has_many :characters, through: :casts
  has_one_attached :photo
  belongs_to :genre

  validates :title, uniqueness: true, presence: :true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :films
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/casts_controller.rb
class CastsController < ApplicationController
  def new
    if params[:film_id].present?
      @film = Film.find(params[:film_id])
      @cast = Cast.new
    else
      @character = Character.find(params[:character_id])
      @cast = Cast.new
    end
  end

  def create
    if params[:film_id].present?
      @film = Film.find(params[:film_id])
      @cast = Cast.new(cast_film_params)
      @cast.film = @film
      if @cast.save
        redirect_to film_path(@film)
      else
        render :new
      end
    else
      @character = Character.find(params[:character_id])
      @cast = Cast.new(cast_character_params)
      @cast.character = @character
      if @cast.save
        redirect_to character_path(@character)
      else
        render :new
      end
    end
  end

  def destroy
    @cast = Cast.find(params[:id])
    @cast.destroy
    redirect_to film_path(@cast.film)
  end
  
  private

  def cast_film_params
    params.require(:cast).permit(:comment, :character_id)
  end

  def cast_character_params
    params.require(:cast).permit(:comment, :film_id)
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]

  def index
    if params[:name].present?
      @query = params[:name].capitalize
      @characters = Character.where("name LIKE ?", "%" + @query + "%")
    elsif params[:age].present?
      @query = params[:age]
      @characters = Character.where("age = ?", @query)
    elsif params[:film_id].present?
      @query = params[:film_id]
      @characters = Character.includes(:films).where('films.id = ?', @query).references(:films)
    else
      @characters = Character.all
    end
  end

  def show
    @cast = Cast.new
  end

  def new
    @character = Character.new
  end
  
  def create
    @character = Character.new(character_params)
    if @character.save
      redirect_to character_path(@character)
    else
      render :new
    end
  end

  def edit
  end
  
  def update
    if @character.update(character_params)
      redirect_to character_path(@character)
    else
      render :edit
    end
  end
  
  def destroy
    @character.destroy
    redirect_to characters_path
  end
  
  private

  def character_params
    params.require(:character).permit(:name, :age, :weight, :history, :photo)
  end

  def set_character
    @character = Character.find(params[:id])
  end
  
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: [:show, :edit, :update, :destroy]

  def index
    if params[:name].present?
      @query = params[:name].capitalize
      @films = Film.where("title LIKE ?", "%" + @query + "%")
    elsif params[:genre_id].present?
      @query = params[:genre_id]
      @films = Film.includes(:genre).where('genres.id = ?', @query).references(:genres)
    elsif params[:order].present?
      @query = params[:order]
      if @query == "ASC"
        @films = Film.order(created_at: :asc)
      elsif @query == "DESC"
        @films = Film.order(created_at: :desc)
      else
        @films = Film.all
      end
    else
      @films = Film.all
    end
  end

  def show
    @cast = Cast.new
  end

  def new
    @film = Film.new
  end

  def create
    @film = Film.new(film_params)
    if @film.save
      redirect_to film_path(@film)
    else
      render :new
    end
  end

  def edit
  end
  
  def update
    if @film.update(film_params)
      redirect_to film_path(@film)
    else
      render :edit
    end
  end

  def destroy
    if @film.destroy
      redirect_to films_url
    else
      redirect_to films_url
    end
  end

  private

  def film_params
    params.require(:film).permit(:title, :rating, :photo, :genre_id)
  end

  def set_film
    @film = Film.find(params[:id])
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all
  end

  def show
    @genre = Genre.find(params[:id])
    @film = Film.new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/casts/new.html.erb
<div class="container mt-3">
  <% if params[:film_id].present? %>
    <h1>Agrega un personaje</h1>
    <%= simple_form_for [@film, @cast] do |f| %>
      <%= f.association :character %>
      <%= f.input :comment  %>
      <%= f.submit "Guardar", class: "btn btn-primary"%>
    <% end %>
    <%= link_to "Cancelar", films_path, class: "btn btn-secondary mt-2" %>
  <% else %>
    <h1>Agrega una película</h1>
    <%= simple_form_for [@character, @cast] do |f| %>
      <%= f.association :film %>
      <%= f.input :comment  %>
      <%= f.submit "Guardar", class: "btn btn-primary"%>
    <% end %>
    <%= link_to "Cancelar", characters_path, class: "btn btn-secondary mt-2" %>
  <% end %>
</div>

app/views/characters/_form.html.erb
<%= simple_form_for @character do |f| %>
  <%= f.input :name, label: "Nombre" %>
  <%= f.input :age, label: "Edad" %>
  <%= f.input :weight, label: "Peso" %>
  <%= f.input :history, label: "Historia" %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Guardar", class: "btn btn-primary"%>
<% end %>

app/views/characters/edit.html.erb
<div class="container mt-3">
  <h1>Edita a <%=@character.name %></h1>
  <%= render 'form' %>
  <%= link_to "Cancelar", character_path(@character), class: "btn btn-secondary mt-2" %>

</div>

app/views/characters/index.html.erb
<div class="container mt-3">
  <div class="d-flex align-items-center bd-highlight">
    <h1 class="flex-grow-1 bd-highlight">Personajes</h1>
    <%= link_to "+ Personaje", new_character_path, class: "btn btn-primary bd-highlight" %>
  </div>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    <% @characters.each do |character| %>
      <a href="<%=character_path(character) %>" class="text-decoration-none">
        <div class="col">
          <div class="card mb-3">
            <%= cl_image_tag character.photo.key, class: "card-img-top" %>
            <div class="card-body">
              <h5 class="card-title"><%= character.name %></h5>
            </div>
          </div>
        </div>
      </a>
    <% end %>
  </div>
</div>

app/views/characters/new.html.erb
<div class="container mt-3">
  <h1>Crea un nuevo personaje</h1>
  <%= render 'form' %>
  <%= link_to "Cancelar", characters_path, class: "btn btn-secondary mt-2" %>
</div>


app/views/characters/show.html.erb
<div class="container mt-3">
  <div class="d-flex align-items-center bd-highlight">
    <div class="flex-grow-1 bd-highlight">
      <h1 class="fs-1 pb-0"><%= @character.name %></h1>
    </div>
    <div class="bd-highlight">
      <%= link_to "Editar", edit_character_path(@character), class: "btn btn-primary" %>
      <%= link_to "Borrar" , character_path(@character), method: :delete, data: { confirm: "¿Está seguro?" }, class: "btn btn-danger ms-2" %>
      <%= link_to "Volver", characters_path, class: "btn btn-secondary ms-2" %>
    </div>
  </div>
  <table class="table">
    <tbody>
      <tr>
        <th scope="row">Age</th>
        <td><%= @character.age %></td>
      </tr>
      <tr>
        <th scope="row">Weight</th>
        <td><%= @character.weight %></td>
      </tr>
      <tr>
        <th scope="row">Historia</th>
        <td><%= @character.history %></td>
      </tr>
    </tbody>
  </table>
  <div class="row row-cols-1 row-cols-md-3 g-4 my-2">
    <% @character.films.each do |film| %>
      <% cast = Cast.find_by(film: film, character: @character) %>
      <div class="col">
        <div class="card mb-3">
          <%= cl_image_tag film.photo.key, class: "card-img-top" %>
          <div class="card-body">
            <h5 class="card-title"><%= film.title %></h5>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/films/_form.html.erb
<%= simple_form_for @film do |f| %>
  <%= f.input :title, label: "Título" %>
  <%= f.input :rating, label: "Rating" %>
  <%= f.association :genre, label: "Género"  %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Guardar", class: "btn btn-primary"%>
<% end %>

app/views/films/edit.html.erb
<div class="container mt-3">
  <h1>Edita a <%=@film.title %></h1>
  <%= render 'form' %>
  <%= link_to "Cancelar", film_path(@film), class: "btn btn-secondary mt-2" %>

</div>

app/views/films/index.html.erb
<div class="container mt-3">
  <div class="d-flex align-items-center bd-highlight">
    <h1 class="flex-grow-1 bd-highlight">Películas</h1>
    <%= link_to "+ Pelicula", new_film_path, class: "btn btn-primary bd-highlight" %>
  </div>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    <% @films.each do |film| %>
      <a href="<%= film_path(film)%>" class="text-decoration-none">
        <div class="col">
          <div class="card mb-3">
            <%= cl_image_tag film.photo.key, class: "card-img-top" %>
            <div class="card-body">
              <h5 class="card-title"><%= film.title %></h5>
              <p class="card-text"><%= film.created_at %></p>
            </div>
          </div>
        </div>
      </a>
    <% end %>
  </div>
</div>

app/views/films/new.html.erb
<div class="container mt-3">
  <h1>Crea un nueva película</h1>
  <%= render 'form' %>
  <%= link_to "Cancelar", films_path, class: "btn btn-secondary mt-2" %>
</div>


app/views/films/show.html.erb
<div class="container mt-3">
  <div class="d-flex align-items-center bd-highlight">
    <div class="flex-grow-1 bd-highlight">
      <h1 class="fs-1 pb-0"><%= @film.title %></h1>
    </div>
    <div class="bd-highlight">
      <%= link_to '+ Personaje', new_film_cast_path(@film), class: "btn btn-primary"  %>
      <%= link_to "Editar", edit_film_path(@film), class: "btn btn-primary ms-2" %>
      <%= link_to "Borrar" , film_path(@film), method: :delete, data: { confirm: "¿Está seguro?" }, class: "btn btn-danger ms-2" %>
      <%= link_to "Volver", films_path, class: "btn btn-secondary ms-2" %>
    </div>
  </div>
  <div class="row row-cols-1 row-cols-md-3 g-4 my-2">
    <% @film.characters.each do |character| %>
      <% cast = Cast.find_by(film: @film, character: character) %>
      <div class="col">
        <div class="card mb-3">
          <%= cl_image_tag character.photo.key, class: "card-img-top" %>
          <div class="card-body">
            <h5 class="card-title"><%= character.name %></h5>
          </div>
          <div class="card-body">
            <small class="text-right flex-shrink-0"><%= link_to 'delete', cast_path(cast), method: :delete, data: { confirm: "Are you sure you want to remove #{character.name} from #{@film.title}"}, class: 'text-danger' %></small>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/genres/index.html.erb
<div class="container mt-3">
  <div class="d-flex align-items-center bd-highlight">
    <h1 class="flex-grow-1 bd-highlight">Géneros</h1>
  </div>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    <% @genres.each do |genre| %>
      <a href="<%= genre_path(genre)%>" class="text-decoration-none">
        <div class="col">
          <div class="card mb-3">
            <%= cl_image_tag genre.photo.key, class: "card-img-top" %>
            <div class="card-body">
              <h5 class="card-title"><%= genre.name %></h5>
            </div>
          </div>
        </div>
      </a>
    <% end %>
  </div>
</div>

app/views/genres/show.html.erb
<div class="container mt-3">
  <div class="d-flex align-items-center bd-highlight">
    <div class="flex-grow-1 bd-highlight">
      <h1 class="fs-1 pb-0"><%= @genre.name %></h1>
    </div>
  </div>
  <div class="row row-cols-1 row-cols-md-3 g-4 my-2">
    <% @genre.films.each do |film| %>
      <div class="col">
        <div class="card mb-3">
          <%= cl_image_tag film.photo.key, class: "card-img-top" %>
          <div class="card-body">
            <h5 class="card-title"><%= film.title %></h5>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Disney API</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container mt-3">
  <h1>Pages#home</h1>
  <p>Find me in app/views/pages/home.html.erb</p>
  <%= link_to 'Personajes', characters_path %>
  <%= link_to 'Películas', films_path %>
  <%= link_to 'Géneros', genres_path %>

</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "DISNEY API", root_path , class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Películas", films_path , class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Personajes", characters_path , class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Géneros", genres_path , class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.email %>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to "Perfil", "", class: "dropdown-item" %></li>
            <li><%= link_to "Config", "", class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
          </ul>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>